### PR TITLE
[WIP] JDBC on spark

### PR DESCRIPTION
**Pull request by ajnavarro**

### CODE REVIEW

**Comment by ajnavarro** [comment]
# Merge https://github.com/src-d/berserker/pull/3 first

**Comment by bzz** [comment]
Wow, that's a lot of code :)

At the quick glance - this seems more complex than what was discussed in https://github.com/src-d/backlog/issues/798#issuecomment-309915788  Could you please elaborate a bit, why the proposed simple solution is not a good fit for us?

From my experience the more code you have - the harder it is to maintain and slower to iterate and that is something we already see in other parts of pipeline.

In any case, do you think it would be possible to get back to #2 first, address the reviews and merge it and then come back to this one?

**Comment by smola** [comment]
Talked with @ajnavarro offline, we can use it a view for references in the database and avoid all the JSON mess in Spark. We would also reduce network usage.

**Comment by bzz** [comment]
Good point and thank you for brining it back to the issue!

But for a quick start - do you think we could modify Scala part (to avoid JSON) to fetch only an IDs and send them to Go? Go will make extra DB request and get references - this would add us ability to test it and-to-end at scale very easy. This will also give us time for implement changes with view in DB.

What do you think?

**Comment by bzz** [comment]
Closing this one due to #20

**Pull request closed without merging**
