### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by bzz**
~Add Apache 2.0 license, but as noted by @smola in https://github.com/src-d/berserker/pull/11#issuecomment-315057285 it might actually need to be a GPL.~

~Waiting clarification from @mcuadros~

After clarification offline - src-d will be releasing Berserker under GPL-3 license

### CODE REVIEW

**Comment by bzz** [comment]
@mcuadros friendly 2 weeks ping

**Comment by bzz** [comment]
This case of sharing a code with Babelfish makes a nice argument why Berserker may be GPL3 https://github.com/src-d/berserker/pull/22#discussion_r130279337

Still need help interpreting https://github.com/src-d/guide/blob/master/engineering/licensing.md#licence

> GPL3 ... specific to language analysis, machine learning and other core parts of our stack

This seems applicable

> and may be used through a client library owned by us allowing interaction with the project to third-party proprietary code

this seems a bit less clear, in case a tool for `Large-scale UAST extraction`, which is a Apache Spark job that talks to enry and bblfsh though gRPC.

**Comment by mcuadros** [comment]
this can be GPLv3 right?

**Comment by bzz** [comment]
Technically I do not see any restrictions right now, why it can not be GPL. So yes, I believe it can, but I do not have much experience with GPL though.

It has Enry gRPC server impl, which could be nice to move to Enry project  (Apache 2.0) eventually as one more build target, but as a copyright holders src-d could re-license that part of code, in case one day we decide to do so.

**Comment by bzz** [comment]
Now, more I think about it - we have only 1 source code dependency in Berserker which is not owned by src-d and is not GPL.

As we used Proteus for gRPC and keep Enry server inside Berserker codebase (#22) - we will have to keep `gogo/protobuf/gogoproto/gogo.proto` file as well https://github.com/src-d/berserker/pull/22/files#diff-2b40fe2809519a9005b1799fea36042aR17 which seems like BSD-style license. 

It seems like 2-clause BSD and thus is *GPL-compatible*.

**Comment by smola** [comment]
@bzz As decided before, let's go with GPLv3.

**Comment by bzz** [comment]
History re-written, PR description updated, GPL-3 text from [src-d/guide](https://github.com/src-d/guide/blob/master/engineering/documents/gpl/LICENSE) template added in 76179a8

If there is there is nothing else, it looks like ok to merge now.

**Review by smola — APPROVED** [review]

**Pull request merged**
